title: "WB"
description: "Apuntes y prácticas del curso de Graficación"

remote_theme: "just-the-docs/just-the-docs"

markdown: kramdown

just_the_docs:
  theme_mode: dark
  search_enabled: true
  logo: false
  aux_links:
    "Ver en GitHub":
      - "https://github.com/GabrielChaconA/WEB"
